### ISSUE TITLE
I CANT LOGOUT PLZ HALP

### ISSUE THREAD

**Issue by rswiernik** [ComputerScienceHouse/CSHMembersPortal#52]
So in the past you were able to use the logout button at the top of the members page. This does not currently work, however, as members.csh.rit.edu/logout does not send you to the proper page. It should send you to webauth.csh.rit.edu/logout which will properly log you out (I just tried it, it works).

**Comment by rswiernik** [comment]
Issue addressed in commit above, closing issue.

**Comment by agargiulo** [comment]
Still an issue until someone pulls the changes onto the webserver.

**Comment by bencentra** [comment]
It looked like it was already done, but I git pulled again just to be safe. Hard-refresh members in your browser if you have to.

**Comment by agargiulo** [comment]
Ah, yeah, works now thanks.
